# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMFApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMFApp
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database', '~> 8.0'
  pod 'FirebaseUI/Auth', '~> 8.0'
  pod 'FirebaseUI/Email'
  
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'QRCode'
  pod 'QRCodeReader.swift', '~> 10.1.0'
  
  target 'SMFAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SMFAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
